export const PaymentStatus = {
  PENDING: 'PENDING',
  ORDER_CREATED: 'ORDER_CREATED',
  PAYMENT_AUTHORIZED: 'PAYMENT_AUTHORIZED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  RETRY_ALLOWED: 'RETRY_ALLOWED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_PROCESSING: 'REFUND_PROCESSING',
  REFUNDED: 'REFUNDED'
} as const;

export type PaymentStatusType = typeof PaymentStatus[keyof typeof PaymentStatus];
